export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESEND_OTP_FORGOTPASSWORD = "RESEND_OTP_FORGOTPASSWOR";
export const VERIFY_FORGOTPASSWORD = "VERIFY_FORGOTPASSWORD";
